development:
  adapter: postgresql
  encoding: unicode
  database: mfapp-dev
  pool: 5
  username: ak
  password: leAN

test:
  adapter: postgresql
  encoding: unicode
  database: mfapp-test
  pool: 5
  username: ak
  password: leAN

production:
  adapter: postgresql
  encoding: unicode
  database: mfapp-prod
  pool: 5
  username: ak
  password: leAN